[package]
name = "ratchet-ground"
version = "0.1.0"
edition = "2021"

[dependencies]
ratchet = { path = "../ratchet-core" }

serde.workspace = true
serde_json = "1.0.122"
strum.workspace = true
strum_macros = "0.26.4"
tch = "0.16.0"
